version: "3.8"
volumes:
  postgis_data:
  data:
  data-2:

services:
  postgres:
    image: "postgres:latest"
    deploy:
      placement:
        constraints:
          - "node.hostname==worker1"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: target
      POSTGRES_PASSWORD: target
    volumes:
      - postgis_data:/var/lib/postgresql/data/
    networks:
      - postgres

  mongo:
    image: mongo
    restart: always
    deploy:
      placement:
        constraints:
          - "node.hostname==worker1"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo

  mysql:
    image: mysql:5.6
    restart: always
    deploy:
      placement:
        constraints:
          - "node.hostname==worker1"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    networks:
      - mysql

  mysql-2:
    image: mysql:5.6
    restart: always
    deploy:
      placement:
        constraints:
          - "node.hostname==worker1"
    volumes:
      - data-2:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test2
    networks:
      - mysql

networks:
  mongo:
    external: true
  postgres:
    external: true
  mysql:
    external: true
