version: "3.8"

services:
  pgadmin:
    image: "dpage/pgadmin4:6.21"
    deploy:
      placement:
        constraints:
          - "node.hostname==worker2"
    environment:
      PGADMIN_DEFAULT_EMAIL: target@targetso.com
      PGADMIN_DEFAULT_PASSWORD: target
    ports:
      - "8080:80"
    networks:
      - postgres

  mongo-express:
    image: mongo-express
    deploy:
      placement:
        constraints:
          - "node.hostname==worker2"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mongo

  adminer:
    image: adminer
    deploy:
      placement:
        constraints:
          - "node.hostname==worker2"
    ports:
      - 8087:8080
    networks:
      - mysql

volumes:
  data:
  data-old:

networks:
  mongo:
    external: true
  postgres:
    external: true
  mysql:
    external: true
